server:
  port: 8090
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mes?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
#      &serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: "0000"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=宝钢数据库
#    url: jdbc:sqlserver://127.0.0.1:52568;DatabaseName=宝钢数据库
    username: sa
    password: sa12345678
    hikari:
      connection-timeout: 1000
      validation-timeout: 1000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 3
      minimum-idle: 1
  #thymelea模板配置
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates
    suffix: .html
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
mybatis:
  mapper-locations: classpath:mapper/*.xml

  # 插件配置 pagehelper
pagehelper:
  helper-dialect: sqlserver
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true
